apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-serviceability
  namespace: rook-ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ocs-serviceability
  template:
    metadata:
      labels:
        name: ocs-serviceability
    spec:
      serviceAccountName: ocs-serviceability
      containers:
        - name: ocs-serviceability
          # Replace this with the built image name
          image: ashishranjan738/ocs-serviceability:latest
          command:
          - ocs-serviceability
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ocs-serviceability"
