apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ocs-serviceability
  namespace: rook-ceph
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'