kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-serviceability
  namespace: rook-ceph
subjects:
- kind: ServiceAccount
  name: ocs-serviceability
  namespace: rook-ceph
roleRef:
  kind: Role
  name: ocs-serviceability
  namespace: rook-ceph
  apiGroup: rbac.authorization.k8s.io
